import { IClient } from "../features/clients/clientsSlice.ts";
import { IUser } from "../features/users/usersSlice.ts";

export const DBUsers: IUser[] = [
  {
    id: "bvfdvfvgf",
    username: "admin",
    password: "admin",
  },
];
export const DBClients: IClient[] = [
  {
    id: 1,
    name: "Alice Smith",
    company: "Tech Innovations",
    contacts: "alice@techinnovations.com",
    description: "Заметки по клиенту",
    userId: "bvfdvfvgf",
  },
  {
    id: 2,
    name: "Bob Johnson",
    company: "Creative Solutions",
    contacts: "bob@creativesolutions.com",
    description: "Заметки по клиенту",
    userId: "bvfdvfvgf",
  },
  {
    id: 3,
    name: "Charlie Brown",
    company: "Web Services Inc.",
    contacts: "charlie@webservices.com",
    description: "Заметки по клиенту",
    userId: "bvfdvfvgf",
  },
  {
    id: 4,
    name: "Diana Prince",
    company: "Marketing Gurus",
    contacts: "diana@marketinggurus.com",
    description: "Заметки по клиенту",
    userId: "bvfdvfvgf",
  },
  {
    id: 5,
    name: "Edward Elric",
    company: "Alchemy Corp",
    contacts: "edward@alchemycorp.com",
    description: "Заметки по клиенту",
    userId: "bvfdvfvgf",
  },
  {
    id: 6,
    name: "Fiona Glenanne",
    company: "Security Experts",
    contacts: "fiona@securityexperts.com",
    description: "Заметки по клиенту",
    userId: "bvfdvfvgf",
  },
  {
    id: 7,
    name: "George Washington",
    company: "Finance Solutions",
    contacts: "george@financesolutions.com",
    description: "Заметки по клиенту",
    userId: "bvfdvfvgf",
  },
  {
    id: 8,
    name: "Hannah Montana",
    company: "Entertainment LLC",
    contacts: "hannah@entertainmentllc.com",
    description: "Заметки по клиенту",
    userId: "bvfdvfvgf",
  },
  {
    id: 9,
    name: "Isaac Newton",
    company: "Scientific Research",
    contacts: "isaac@scientificresearch.com",
    description: "Заметки по клиенту",
    userId: "bvfdvfvgf",
  },
  {
    id: 10,
    name: "Jack Sparrow",
    company: "Pirate Ventures",
    contacts: "jack@pirateventures.com",
    description: "Заметки по клиенту",
    userId: "bvfdvfvgf",
  },
  {
    id: 11,
    name: "Katherine Johnson",
    company: "Data Analytics",
    contacts: "katherine@dataanalytics.com",
    description: "Заметки по клиенту",
    userId: "bvfdvfvgf",
  },
  {
    id: 12,
    name: "Liam Neeson",
    company: "Film Productions",
    contacts: "liam@filmproductions.com",
    description: "Заметки по клиенту",
    userId: "bvfdvfvgf",
  },
  {
    id: 13,
    name: "Mona Lisa",
    company: "Art Gallery",
    contacts: "mona@artgallery.com",
    description: "Заметки по клиенту",
    userId: "bvfdvfvgf",
  },
  {
    id: 14,
    name: "Nathan Drake",
    company: "Adventure Co.",
    contacts: "nathan@adventureco.com",
    description: "Заметки по клиенту",
    userId: "bvfdvfvgf",
  },
  {
    id: 15,
    name: "Olivia Pope",
    company: "Legal Advisors",
    contacts: "olivia@legaladvisors.com",
    description: "Заметки по клиенту",
    userId: "bvfdvfvgf",
  },
  {
    id: 16,
    name: "Peter Parker",
    company: "Photography Studio",
    contacts: "peter@photographystudio.com",
    description: "Заметки по клиенту",
    userId: "bvfdvfvgf",
  },
  {
    id: 17,
    name: "Quinn Fabray",
    company: "Fashion House",
    contacts: "quinn@fashionhouse.com",
    description: "Заметки по клиенту",
    userId: "bvfdvfvgf",
  },
  {
    id: 18,
    name: "Robert Langdon",
    company: "Mystery Consultants",
    contacts: "robert@mysteryconsultants.com",
    description: "Заметки по клиенту",
    userId: "bvfdvfvgf",
  },
  {
    id: 19,
    name: "Sarah Connor",
    company: "Tech Solutions",
    contacts: "sarah@techsolutions.com",
    description: "Заметки по клиенту",
    userId: "bvfdvfvgf",
  },
  {
    id: 20,
    name: "Tony Stark",
    company: "Stark Industries",
    contacts: "tony@starkindustries.com",
    description: "Заметки по клиенту",
    userId: "bvfdvfvgf",
  },
];
